service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    getOrder:
        handler: new_order.php
        description: 'Fetches orders from order API'
        layers:
            - ${bref:layer.php-74}
    updateOrder:
        handler: update_order.php
        description: 'updates orders on order API'
        layers:
            - ${bref:layer.php-74}
    getInventory:
        handler: inventory.php
        description: 'Fetches Inventory from Inventory API'
        layers:
            - ${bref:layer.php-74}
    matchItemWithInventory:
        handler: match_Item_Inventory.php
        description: 'Fetches Inventory from Inventory API'
        layers:
            - ${bref:layer.php-74}


# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
